networks:
  webapp:

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - "./nginx:/etc/nginx/conf.d/"
      - "./../src/api:/app"
    container_name: ${APP_NAME}-web
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - webapp
  php:
    image: bitnami/php-fpm:8.1
    container_name: ${APP_NAME}-api
    volumes:
      - "./../src/api:/app"
    working_dir: "/app"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - webapp
  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}-db
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}}
    volumes:
      - "./../data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - webapp
